###
POST https://encontro-backend-aysb.onrender.com/notification
Content-Type: application/json

{
    "to":"marcosmarinho19998@gmail.com",
    "subject":"marcosmarinho19998@gmail.com"
}


####
POST http://localhost:3000/notification
Content-Type: application/json

{
    "to":"marcosmarinho19998@gmail.com",
    "subject":"marcosmarinho19998@gmail.com"
}
